# Copyright 2025 The zb Authors
# SPDX-License-Identifier: MIT

[build]
command = 'CGO_ENABLED=0 PATH="$(go env GOPATH)/bin:$PATH" make -j1 install-woosh html'
publish = "_build/html"

[build.environment]
GO_VERSION = "1.26.3"
PYTHON_VERSION = "3.13.13"
