# Copyright 2025 The zb Authors
# SPDX-License-Identifier: MIT

[build]
command = 'make install-woosh && PATH="$(go env GOBIN):$PATH" make html'
publish = "_build/html"

[build.environment]
GO_VERSION = "1.26.3"
PYTHON_VERSION = "3.13.13"
