[theme]
inherit = "basic"
stylesheets = [
  "zb.css",
]
sidebars = [
  "about.html",
  "searchfield.html",
  "navigation.html",
]

[theme.pygments_style]
default = "zbtheme.support.ZB"
dark = "zbtheme.support.ZBDark"

[options]
github_banner = false
github_button = true
github_repo = ""
github_user = ""
